/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'
import { useSpring, a } from 'react-spring/three'

// Chest Sound
import chestOpenSound from '../../assets/sound/open-chest.mp3'
import chestCloseSound from '../../assets/sound/close-chest.mp3'
const openChest = new Audio(chestOpenSound)
const closeChest = new Audio(chestCloseSound)

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('../../../coffre-minecraft.glb')

  // Open function
  const handleOpen = () => {
    props.setOpen(!props.open)
    openChest.volume = 0.3
    closeChest.volume = 0.3

    props.open ? openChest.play() : closeChest.play()
  }

  const openChestAnimation = useSpring({
    rotation: props.open ? [0, 0, 0] : [1.61, 0, 0],
    position: props.open ? [0, -1.5, 0] : [0, 0, 0],
  })

  return (
    <group onClick={handleOpen} ref={group} {...props} dispose={null}>
      <a.group rotation={openChestAnimation.position} position={[0, -0.99, 0]}>
        <primitive object={nodes.Bone} />
        <a.primitive rotation={openChestAnimation.rotation} object={nodes.Bone001} />
        <skinnedMesh
          castShadow
          material={materials.Material}
          geometry={nodes.Cube.geometry}
          skeleton={nodes.Cube.skeleton}
        />
      </a.group>
    </group>
  )
}

useGLTF.preload('../../../coffre-minecraft.glb')
